#!/usr/bin/env python 
# -*- coding:utf-8 -*-
from rdkit import Chem
from rdkit.Chem import QED
import seaborn as sns
import matplotlib.pyplot as plt



id = Chem.SDMolSupplier('C:/Users/chiny/Desktop/4inject_pro.sdf')
od = Chem.SDMolSupplier('C:/Users/chiny/Desktop/4oral_pro.sdf')
i_mols = []
o_mols = []
for mol in id:
    a = QED.default(mol)
    i_mols.append(a)
for mol in od:
    a = QED.default(mol)
    o_mols.append(a)

sns.distplot(i_mols, bins= 200 ,hist=False)
plt.savefig("1.png")
plt.show()
